name: "Create issues from todos"
on: ["push"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "Create issues from todos"
        uses: "alstr/todo-to-issue-action@v4.6.6"
        id: "todo"
